apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl 
spec:
  selector:
     matchLabels:
       app: mysql8
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db_name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql8-service
spec:
  type: NodePort
  selector:
    app: mysql8
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
