name: Build Web Server and Deploy to Minikube

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Build and deploy the web server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Test if cluster is up
        run: kubectl get pods -A
      - name: Create secret configuration file
        run: |
          kubectl apply -f secret.yaml
          echo "Verify that secret is created"
          kubectl get secret
      - name: Deploy db to minikube
        run: |
          kubectl apply -f deployment-db.yaml
          kubectl get pods
          kubectl get services
      - name: Build docker image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker compose build
          echo -n "Check if the image are available"
          docker image ls
      - name: Deploy to minikube
        run: kubectl apply -f deployment-web-server.yaml
      - name: Wait for containers to deploy for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check availability of the created pods and services
        run: kubectl get all
      - name: Connect to Postgres DB
        run:
          POD=$(kubectl get pod -l app=web -o jsonpath="{.items[0].metadata.name}")
          echo "$POD"
          kubectl exec -ti $POD -- ls /
      - name: Get web service URL
        run: |
          minikube service list
          minikube service web-service --url
          minikube status
          curl $(minikube service web-service --url)
